name: dashboard_pwa
description: SaaS dashboard for WhatsApp bot configuration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  google_fonts: ^6.2.1
  http: ^1.2.2
  http_parser: ^4.1.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true