import 'dart:convert';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:url_launcher/url_launcher.dart';

import '../services/api_service.dart';
import '../widgets/app_text_field.dart';
import '../widgets/section_card.dart';
import '../widgets/secondary_page_layout.dart';

class CompanyContextPage extends StatefulWidget {
  const CompanyContextPage({
    super.key,
    required this.apiService,
    required this.onConfigUpdated,
    this.onRequestBack,
  });

  final ApiService apiService;
  final VoidCallback onConfigUpdated;
  final VoidCallback? onRequestBack;

  @override
  State<CompanyContextPage> createState() => _CompanyContextPageState();
}

abstract class CompanyContextPageStateAccess {
  void openUsageRulesEditor();
}

class _CompanyContextPageState extends State<CompanyContextPage>
    implements CompanyContextPageStateAccess {
  final TextEditingController _companyNameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _whatsappController = TextEditingController();
  final TextEditingController _addressController = TextEditingController();
  final TextEditingController _latitudeController = TextEditingController();
  final TextEditingController _longitudeController = TextEditingController();
  final TextEditingController _mapsLinkController = TextEditingController();
  final TextEditingController _workingHoursController = TextEditingController();
  final TextEditingController _usageRulesController = TextEditingController();

  final List<_BankAccountFormRow> _bankAccounts = <_BankAccountFormRow>[];
  final List<_ImageFormRow> _images = <_ImageFormRow>[];

  bool _isLoading = true;
  bool _isSaving = false;
  bool _isLocating = false;
  final Set<_ImageFormRow> _uploadingImages = <_ImageFormRow>{};
  final Set<_BankAccountFormRow> _uploadingBankImages = <_BankAccountFormRow>{};
  String? _lastAutoGeneratedMapsLink;
  String? _loadError;

  @override
  void initState() {
    super.initState();
    _latitudeController.addListener(_syncMapsLinkPreview);
    _longitudeController.addListener(_syncMapsLinkPreview);
    _loadContext();
  }

  @override
  void didUpdateWidget(covariant CompanyContextPage oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.apiService.baseUrl != widget.apiService.baseUrl) {
      _loadContext();
    }
  }

  @override
  void dispose() {
    _companyNameController.dispose();
    _descriptionController.dispose();
    _phoneController.dispose();
    _whatsappController.dispose();
    _addressController.dispose();
    _latitudeController.dispose();
    _longitudeController.dispose();
    _mapsLinkController.dispose();
    _workingHoursController.dispose();
    _usageRulesController.dispose();
    _disposeBankAccounts();
    _disposeImages();
    super.dispose();
  }

  Future<void> _loadContext() async {
    setState(() {
      _isLoading = true;
      _loadError = null;
    });

    try {
      final context = await widget.apiService.getCompanyContext();
      _applyContext(context);
    } catch (error) {
      _applyContext(CompanyContextData.empty());
      if (!mounted) {
        return;
      }

      setState(() {
        _loadError = error.toString().replaceFirst('Exception: ', '');
      });
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  void _applyContext(CompanyContextData context) {
    _companyNameController.text = context.companyName;
    _descriptionController.text = context.description;
    _phoneController.text = context.phone;
    _whatsappController.text = context.whatsapp;
    _addressController.text = context.address;
    _latitudeController.text = context.latitude?.toString() ?? '';
    _longitudeController.text = context.longitude?.toString() ?? '';
    _mapsLinkController.text = context.googleMapsLink;
    _lastAutoGeneratedMapsLink =
      context.googleMapsLink.trim().isNotEmpty &&
        context.googleMapsLink.trim() == _buildGeneratedMapsLinkFromCoordinates()
      ? context.googleMapsLink.trim()
      : null;
    _workingHoursController.text = _prettyJson(context.workingHoursJson);
    _usageRulesController.text = _prettyJson(context.usageRulesJson);

    _disposeBankAccounts();
    _disposeImages();

    for (final item in context.bankAccountsJson) {
      _bankAccounts.add(_BankAccountFormRow.fromData(item));
    }
    for (final item in context.imagesJson) {
      _images.add(_ImageFormRow.fromData(item));
    }

    if (_bankAccounts.isEmpty) {
      _bankAccounts.add(_BankAccountFormRow.empty());
    }
    if (_images.isEmpty) {
      _images.add(_ImageFormRow.empty());
    }

    _syncMapsLinkPreview();
  }

  Future<void> _saveContext() async {
    setState(() {
      _isSaving = true;
    });

    try {
      final workingHours = _decodeJsonMap(
        _workingHoursController.text,
        fieldName: 'Horario',
      );
      final usageRules = _decodeJsonMap(
        _usageRulesController.text,
        fieldName: 'Reglas de uso',
      );
      final latitude = _parseCoordinate(
        _latitudeController.text,
        fieldName: 'Latitud',
      );
      final longitude = _parseCoordinate(
        _longitudeController.text,
        fieldName: 'Longitud',
      );
      final bankAccounts = _bankAccounts
          .map((item) => item.toJson())
          .where((item) => item.isNotEmpty)
          .toList();
      final images = _images
          .map((item) => item.toJson())
          .where((item) => item.isNotEmpty)
          .toList();

      final saved = await widget.apiService.saveCompanyContext(
        companyName: _companyNameController.text.trim(),
        description: _descriptionController.text.trim(),
        phone: _phoneController.text.trim(),
        whatsapp: _whatsappController.text.trim(),
        address: _addressController.text.trim(),
        googleMapsLink: _mapsLinkController.text.trim(),
        latitude: latitude,
        longitude: longitude,
        workingHoursJson: workingHours,
        bankAccountsJson: bankAccounts,
        imagesJson: images,
        usageRulesJson: usageRules,
      );

      if (!mounted) {
        return;
      }

      _applyContext(saved);
      widget.onConfigUpdated();
      _showMessage('Informacion de la empresa guardada.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _isSaving = false;
        });
      }
    }
  }

  Future<void> _captureLocation() async {
    setState(() {
      _isLocating = true;
    });

    try {
      final servicesEnabled = await Geolocator.isLocationServiceEnabled();
      if (!servicesEnabled) {
        throw Exception('Activa la ubicacion del dispositivo para obtener el GPS.');
      }

      var permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
      }

      if (permission == LocationPermission.denied ||
          permission == LocationPermission.deniedForever) {
        throw Exception('No se concedio permiso para leer la ubicacion.');
      }

      final position = await Geolocator.getCurrentPosition();
      _latitudeController.text = position.latitude.toStringAsFixed(6);
      _longitudeController.text = position.longitude.toStringAsFixed(6);
      _syncMapsLinkPreview();

      if (!mounted) {
        return;
      }

      _showMessage('Ubicacion obtenida. Guarda para persistir el enlace de mapa.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _isLocating = false;
        });
      }
    }
  }

  Future<void> _openMapsLink() async {
    final link = _mapsLinkController.text.trim();
    if (link.isEmpty) {
      _showMessage('Todavia no hay enlace de mapa disponible.', isError: true);
      return;
    }

    final launched = await launchUrl(Uri.parse(link));
    if (!launched && mounted) {
      _showMessage('No se pudo abrir Google Maps.', isError: true);
    }
  }

  @override
  void openUsageRulesEditor() {
    _showUsageRulesSheet();
  }

  Future<void> _showUsageRulesSheet() async {
    final controller = TextEditingController(text: _usageRulesController.text.trim());

    await showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      showDragHandle: true,
      builder: (context) {
        final viewInsets = MediaQuery.viewInsetsOf(context);
        return Padding(
          padding: EdgeInsets.fromLTRB(20, 12, 20, 24 + viewInsets.bottom),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              const Text(
                'Reglas de uso del bot',
                style: TextStyle(
                  color: Color(0xFF0F172A),
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 8),
              const Text(
                'Estas reglas limitan cuando el bot puede usar informacion de la empresa.',
                style: TextStyle(
                  color: Color(0xFF64748B),
                  fontSize: 13,
                  height: 1.45,
                ),
              ),
              const SizedBox(height: 18),
              TextField(
                controller: controller,
                maxLines: 12,
                decoration: const InputDecoration(
                  hintText:
                      '{\n  "send_location": "solo_si_cliente_la_pide",\n  "send_bank_accounts": "solo_si_cliente_quiere_pagar"\n}',
                ),
              ),
              const SizedBox(height: 18),
              Wrap(
                spacing: 12,
                runSpacing: 12,
                children: <Widget>[
                  ElevatedButton(
                    onPressed: () {
                      _usageRulesController.text = controller.text.trim();
                      Navigator.of(context).pop();
                    },
                    child: const Text('Aplicar'),
                  ),
                  OutlinedButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Cerrar'),
                  ),
                ],
              ),
            ],
          ),
        );
      },
    );

    controller.dispose();
  }

  void _addBankAccount() {
    setState(() {
      _bankAccounts.add(_BankAccountFormRow.empty());
    });
  }

  void _removeBankAccount(_BankAccountFormRow row) {
    if (_bankAccounts.length == 1) {
      row.clear();
      setState(() {});
      return;
    }

    setState(() {
      _bankAccounts.remove(row);
      row.dispose();
    });
  }

  void _addImage() {
    setState(() {
      _images.add(_ImageFormRow.empty());
    });
  }

  Future<void> _uploadImageForRow(_ImageFormRow row) async {
    setState(() {
      _uploadingImages.add(row);
    });

    try {
      final uploadedUrl = await _pickAndUploadImage(
        titlePrefix: _companyNameController.text.trim().isEmpty
            ? 'Imagen empresa'
            : 'Imagen ${_companyNameController.text.trim()}',
      );
      if (uploadedUrl == null) {
        return;
      }

      row.urlController.text = uploadedUrl;
      if (!mounted) {
        return;
      }

      _showMessage('Imagen cargada correctamente.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _uploadingImages.remove(row);
        });
      }
    }
  }

  Future<void> _uploadBankAccountImage(_BankAccountFormRow row) async {
    setState(() {
      _uploadingBankImages.add(row);
    });

    try {
      final uploadedUrl = await _pickAndUploadImage(
        titlePrefix: row.bankController.text.trim().isEmpty
            ? 'Soporte cuenta bancaria'
            : 'Soporte ${row.bankController.text.trim()}',
      );
      if (uploadedUrl == null) {
        return;
      }

      row.imageController.text = uploadedUrl;
      if (!mounted) {
        return;
      }

      _showMessage('Imagen de cuenta cargada correctamente.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _uploadingBankImages.remove(row);
        });
      }
    }
  }

  void _removeImage(_ImageFormRow row) {
    if (_images.length == 1) {
      row.clear();
      setState(() {});
      return;
    }

    setState(() {
      _images.remove(row);
      row.dispose();
    });
  }

  void _disposeBankAccounts() {
    for (final item in _bankAccounts) {
      item.dispose();
    }
    _bankAccounts.clear();
  }

  void _disposeImages() {
    for (final item in _images) {
      item.dispose();
    }
    _images.clear();
  }

  void _syncMapsLinkPreview() {
    final generated = _buildGeneratedMapsLinkFromCoordinates();
    final current = _mapsLinkController.text.trim();

    if (generated == null) {
      if (current.isEmpty || current == (_lastAutoGeneratedMapsLink ?? '')) {
        _mapsLinkController.clear();
        _lastAutoGeneratedMapsLink = null;
      }
      return;
    }

    if (current.isEmpty || current == (_lastAutoGeneratedMapsLink ?? '')) {
      _mapsLinkController.text = generated;
      _lastAutoGeneratedMapsLink = generated;
    }
  }

  String? _buildGeneratedMapsLinkFromCoordinates() {
    final latitude = double.tryParse(_latitudeController.text.trim());
    final longitude = double.tryParse(_longitudeController.text.trim());

    if (latitude == null || longitude == null) {
      return null;
    }

    return 'https://www.google.com/maps?q=$latitude,$longitude';
  }

  Future<String?> _pickAndUploadImage({required String titlePrefix}) async {
    final result = await FilePicker.platform.pickFiles(
      allowMultiple: false,
      withData: true,
      type: FileType.custom,
      allowedExtensions: const <String>['png', 'jpg', 'jpeg', 'webp', 'svg'],
    );

    final file = result?.files.single;
    if (file == null || file.bytes == null) {
      return null;
    }

    final extension = file.extension?.toLowerCase();
    if (file.size > 20 * 1024 * 1024) {
      throw Exception('La imagen supera el limite de 20MB.');
    }

    final uploaded = await widget.apiService.uploadMedia(
      fileBytes: file.bytes!,
      fileName: file.name,
      contentType: extension == 'png'
          ? 'image/png'
          : extension == 'webp'
              ? 'image/webp'
              : extension == 'svg'
                  ? 'image/svg+xml'
                  : 'image/jpeg',
      title: titlePrefix,
      description: 'Imagen asociada a informacion empresarial',
    );

    return uploaded.fileUrl;
  }

  Map<String, dynamic> _decodeJsonMap(
    String rawValue, {
    required String fieldName,
  }) {
    final trimmed = rawValue.trim();
    if (trimmed.isEmpty) {
      return <String, dynamic>{};
    }

    final decoded = jsonDecode(trimmed);
    if (decoded is! Map<String, dynamic>) {
      throw Exception('$fieldName debe ser un JSON tipo objeto.');
    }

    return decoded;
  }

  double? _parseCoordinate(String rawValue, {required String fieldName}) {
    final trimmed = rawValue.trim();
    if (trimmed.isEmpty) {
      return null;
    }

    final parsed = double.tryParse(trimmed);
    if (parsed == null) {
      throw Exception('$fieldName no es valida.');
    }

    return parsed;
  }

  String _prettyJson(Map<String, dynamic> value) {
    if (value.isEmpty) {
      return '{}';
    }

    return const JsonEncoder.withIndent('  ').convert(value);
  }

  void _showMessage(String message, {bool isError = false}) {
    final messenger = ScaffoldMessenger.of(context);
    messenger.hideCurrentSnackBar();
    messenger.showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? const Color(0xFF9F1239) : const Color(0xFF166534),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isBusy = _isLoading || _isSaving;

    return SecondaryPageLayout(
      caption:
          'Contexto empresarial dinamico para el bot. Se guarda aparte de los prompts y solo debe usarse cuando la intencion del cliente lo amerite.',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          if (_loadError != null)
            Container(
              width: double.infinity,
              margin: const EdgeInsets.only(bottom: 18),
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
              decoration: BoxDecoration(
                color: const Color(0xFFFFFBEB),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: const Color(0xFFFCD34D)),
              ),
              child: Text(
                _loadError!,
                style: const TextStyle(color: Color(0xFF713F12), height: 1.45),
              ),
            ),
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.only(bottom: 16),
              child: LinearProgressIndicator(minHeight: 3),
            ),
          SectionCard(
            title: 'Informacion de la Empresa',
            subtitle:
                'Datos adicionales que el bot puede usar como contexto complementario cuando el cliente lo necesite.',
            child: Column(
              children: <Widget>[
                _buildBasicDataSection(isBusy),
                _buildContactSection(isBusy),
                _buildLocationSection(isBusy),
                _buildWorkingHoursSection(isBusy),
                _buildBankAccountsSection(isBusy),
                _buildImagesSection(isBusy),
                const SizedBox(height: 12),
                Wrap(
                  spacing: 12,
                  runSpacing: 12,
                  children: <Widget>[
                    ElevatedButton(
                      onPressed: isBusy ? null : _saveContext,
                      child: Text(_isSaving ? 'Guardando...' : 'Guardar'),
                    ),
                    OutlinedButton(
                      onPressed: isBusy ? null : _loadContext,
                      child: const Text('Recargar'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBasicDataSection(bool isBusy) {
    return _InnerSection(
      title: '1. Datos basicos',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const _ExampleText(
            text: 'Ejemplo: Nombre comercial: Phyto Emagry. Descripcion: Suplementos para control de peso y orientacion por WhatsApp.',
          ),
          const SizedBox(height: 12),
          LayoutBuilder(
            builder: (context, constraints) {
              final fullWidth = constraints.maxWidth;
              final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

              return Wrap(
                spacing: 18,
                runSpacing: 18,
                children: <Widget>[
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Nombre comercial',
                      controller: _companyNameController,
                      enabled: !isBusy,
                      hintText: 'Phyto Emagry',
                      helperText: 'Ejemplo: Phyto Emagry RD',
                    ),
                  ),
                  SizedBox(
                    width: fullWidth,
                    child: AppTextField(
                      label: 'Descripcion',
                      controller: _descriptionController,
                      enabled: !isBusy,
                      maxLines: 4,
                      hintText: 'Resumen corto de la empresa y lo que ofrece.',
                      helperText: 'Ejemplo: Venta de productos naturales, seguimiento y soporte por WhatsApp.',
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildContactSection(bool isBusy) {
    return _InnerSection(
      title: '2. Contacto',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const _ExampleText(
            text: 'Ejemplo: Telefono: 809-555-1234. WhatsApp: +18095551234.',
          ),
          const SizedBox(height: 12),
          LayoutBuilder(
            builder: (context, constraints) {
              final fullWidth = constraints.maxWidth;
              final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

              return Wrap(
                spacing: 18,
                runSpacing: 18,
                children: <Widget>[
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Telefono',
                      controller: _phoneController,
                      enabled: !isBusy,
                      hintText: '809-555-1234',
                      helperText: 'Ejemplo: 809-555-1234',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'WhatsApp',
                      controller: _whatsappController,
                      enabled: !isBusy,
                      hintText: '+18095551234',
                      helperText: 'Ejemplo: +18095551234',
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildLocationSection(bool isBusy) {
    return _InnerSection(
      title: '3. Ubicacion',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const _ExampleText(
            text: 'Ejemplo: Direccion: Av. Winston Churchill 101, Santo Domingo. Puedes usar GPS o pegar directamente un link de Google Maps.',
          ),
          const SizedBox(height: 12),
          AppTextField(
            label: 'Direccion',
            controller: _addressController,
            enabled: !isBusy,
            maxLines: 2,
            hintText: 'Direccion fisica o punto de referencia.',
            helperText: 'Ejemplo: Av. Winston Churchill 101, Santo Domingo',
          ),
          const SizedBox(height: 18),
          LayoutBuilder(
            builder: (context, constraints) {
              final fullWidth = constraints.maxWidth;
              final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

              return Wrap(
                spacing: 18,
                runSpacing: 18,
                children: <Widget>[
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Latitud',
                      controller: _latitudeController,
                      enabled: !isBusy,
                      keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: true),
                      hintText: '18.486058',
                      helperText: 'Ejemplo: 18.486058',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Longitud',
                      controller: _longitudeController,
                      enabled: !isBusy,
                      keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: true),
                      hintText: '-69.931212',
                      helperText: 'Ejemplo: -69.931212',
                    ),
                  ),
                  SizedBox(
                    width: fullWidth,
                    child: AppTextField(
                      label: 'Link de Google Maps',
                      controller: _mapsLinkController,
                      enabled: !isBusy,
                      helperText:
                          'Ejemplo: https://www.google.com/maps?q=18.486058,-69.931212. Se autogenera con GPS, pero tambien puedes pegarlo manualmente.',
                      hintText: 'Pega aqui tu link de Google Maps si ya lo tienes.',
                    ),
                  ),
                ],
              );
            },
          ),
          const SizedBox(height: 18),
          Wrap(
            spacing: 12,
            runSpacing: 12,
            children: <Widget>[
              ElevatedButton.icon(
                onPressed: isBusy || _isLocating ? null : _captureLocation,
                icon: Icon(_isLocating ? Icons.gps_not_fixed_rounded : Icons.my_location_rounded),
                label: Text(_isLocating ? 'Obteniendo ubicacion...' : 'Obtener ubicacion'),
              ),
              OutlinedButton.icon(
                onPressed: _mapsLinkController.text.trim().isEmpty ? null : _openMapsLink,
                icon: const Icon(Icons.map_outlined),
                label: const Text('Abrir mapa'),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildWorkingHoursSection(bool isBusy) {
    return _InnerSection(
      title: '4. Horario',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const _ExampleText(
            text: 'Ejemplo: lunes a viernes de 8 AM a 6 PM y sabado de 9 AM a 1 PM.',
          ),
          const SizedBox(height: 12),
          AppTextField(
            label: 'working_hours_json',
            controller: _workingHoursController,
            enabled: !isBusy,
            maxLines: 8,
            hintText: '{\n  "lunes_viernes": "8:00 AM - 6:00 PM",\n  "sabado": "9:00 AM - 1:00 PM"\n}',
            helperText: 'Puedes copiar ese ejemplo y cambiar los horarios.',
          ),
        ],
      ),
    );
  }

  Widget _buildBankAccountsSection(bool isBusy) {
    return _InnerSection(
      title: '5. Cuentas bancarias',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const _ExampleText(
            text: 'Ejemplo: Banco: Banreservas. Tipo: Ahorro. Numero: 123456789. Titular: Phyto Emagry SRL. En la imagen puedes subir un comprobante o foto de referencia.',
          ),
          const SizedBox(height: 12),
          for (final item in _bankAccounts) ...<Widget>[
            _BankAccountCard(
              row: item,
              enabled: !isBusy,
              isUploadingImage: _uploadingBankImages.contains(item),
              onUploadImage: () => _uploadBankAccountImage(item),
              onRemove: () => _removeBankAccount(item),
            ),
            const SizedBox(height: 14),
          ],
          OutlinedButton.icon(
            onPressed: isBusy ? null : _addBankAccount,
            icon: const Icon(Icons.add_rounded),
            label: const Text('Agregar cuenta bancaria'),
          ),
        ],
      ),
    );
  }

  Widget _buildImagesSection(bool isBusy) {
    return _InnerSection(
      title: '6. Imagenes',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const _ExampleText(
            text: 'Ejemplo: aqui puedes subir fotos del local, logos o imagenes de apoyo para que queden guardadas como contexto visual.',
          ),
          const SizedBox(height: 12),
          for (final item in _images) ...<Widget>[
            _ImageRowCard(
              row: item,
              enabled: !isBusy,
              isUploading: _uploadingImages.contains(item),
              onUpload: () => _uploadImageForRow(item),
              onRemove: () => _removeImage(item),
            ),
            const SizedBox(height: 14),
          ],
          OutlinedButton.icon(
            onPressed: isBusy ? null : _addImage,
            icon: const Icon(Icons.add_photo_alternate_outlined),
            label: const Text('Agregar imagen'),
          ),
        ],
      ),
    );
  }
}

class _InnerSection extends StatelessWidget {
  const _InnerSection({required this.title, required this.child});

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 26),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(
            title,
            style: const TextStyle(
              color: Color(0xFF0F172A),
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 14),
          child,
        ],
      ),
    );
  }
}

class _ExampleText extends StatelessWidget {
  const _ExampleText({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFC),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Text(
        text,
        style: const TextStyle(
          color: Color(0xFF475569),
          fontSize: 12,
          height: 1.45,
        ),
      ),
    );
  }
}

class _BankAccountCard extends StatelessWidget {
  const _BankAccountCard({
    required this.row,
    required this.enabled,
    required this.isUploadingImage,
    required this.onUploadImage,
    required this.onRemove,
  });

  final _BankAccountFormRow row;
  final bool enabled;
  final bool isUploadingImage;
  final VoidCallback onUploadImage;
  final VoidCallback onRemove;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFC),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: LayoutBuilder(
        builder: (context, constraints) {
          final fullWidth = constraints.maxWidth;
          final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Wrap(
                spacing: 18,
                runSpacing: 18,
                children: <Widget>[
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Banco',
                      controller: row.bankController,
                      enabled: enabled,
                      helperText: 'Ejemplo: Banreservas',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Tipo de cuenta',
                      controller: row.accountTypeController,
                      enabled: enabled,
                      helperText: 'Ejemplo: Ahorro o Corriente',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Numero',
                      controller: row.numberController,
                      enabled: enabled,
                      helperText: 'Ejemplo: 123456789',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Titular',
                      controller: row.holderController,
                      enabled: enabled,
                      helperText: 'Ejemplo: Phyto Emagry SRL',
                    ),
                  ),
                  SizedBox(
                    width: fullWidth,
                    child: AppTextField(
                      label: 'Imagen opcional',
                      controller: row.imageController,
                      enabled: enabled,
                      hintText: 'https://...',
                      helperText: 'Puedes pegar una URL o usar el boton de abajo para subir la imagen aqui mismo.',
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 14),
              Align(
                alignment: Alignment.centerRight,
                child: Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  alignment: WrapAlignment.end,
                  children: <Widget>[
                    OutlinedButton.icon(
                      onPressed: enabled && !isUploadingImage ? onUploadImage : null,
                      icon: Icon(
                        isUploadingImage
                            ? Icons.cloud_upload_outlined
                            : Icons.upload_file_rounded,
                      ),
                      label: Text(
                        isUploadingImage ? 'Subiendo imagen...' : 'Subir imagen aqui',
                      ),
                    ),
                    TextButton.icon(
                      onPressed: enabled ? onRemove : null,
                      icon: const Icon(Icons.delete_outline_rounded),
                      label: const Text('Quitar cuenta'),
                    ),
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}

class _ImageRowCard extends StatelessWidget {
  const _ImageRowCard({
    required this.row,
    required this.enabled,
    required this.isUploading,
    required this.onUpload,
    required this.onRemove,
  });

  final _ImageFormRow row;
  final bool enabled;
  final bool isUploading;
  final VoidCallback onUpload;
  final VoidCallback onRemove;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFC),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          AppTextField(
            label: 'URL de imagen',
            controller: row.urlController,
            enabled: enabled,
            hintText: 'https://...',
            helperText: 'Puedes pegar una URL o usar el boton para subir la imagen.',
          ),
          const SizedBox(height: 10),
          Align(
            alignment: Alignment.centerRight,
            child: Wrap(
              spacing: 8,
              runSpacing: 8,
              alignment: WrapAlignment.end,
              children: <Widget>[
                OutlinedButton.icon(
                  onPressed: enabled && !isUploading ? onUpload : null,
                  icon: Icon(
                    isUploading
                        ? Icons.cloud_upload_outlined
                        : Icons.upload_file_rounded,
                  ),
                  label: Text(isUploading ? 'Subiendo...' : 'Subir imagen'),
                ),
                TextButton.icon(
                  onPressed: enabled ? onRemove : null,
                  icon: const Icon(Icons.delete_outline_rounded),
                  label: const Text('Quitar imagen'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _BankAccountFormRow {
  _BankAccountFormRow({
    required this.bankController,
    required this.accountTypeController,
    required this.numberController,
    required this.holderController,
    required this.imageController,
  });

  factory _BankAccountFormRow.empty() {
    return _BankAccountFormRow(
      bankController: TextEditingController(),
      accountTypeController: TextEditingController(),
      numberController: TextEditingController(),
      holderController: TextEditingController(),
      imageController: TextEditingController(),
    );
  }

  factory _BankAccountFormRow.fromData(CompanyBankAccountData data) {
    return _BankAccountFormRow(
      bankController: TextEditingController(text: data.bank),
      accountTypeController: TextEditingController(text: data.accountType),
      numberController: TextEditingController(text: data.number),
      holderController: TextEditingController(text: data.holder),
      imageController: TextEditingController(text: data.image),
    );
  }

  final TextEditingController bankController;
  final TextEditingController accountTypeController;
  final TextEditingController numberController;
  final TextEditingController holderController;
  final TextEditingController imageController;

  Map<String, dynamic> toJson() {
    final bank = bankController.text.trim();
    final accountType = accountTypeController.text.trim();
    final number = numberController.text.trim();
    final holder = holderController.text.trim();
    final image = imageController.text.trim();

    if (bank.isEmpty &&
        accountType.isEmpty &&
        number.isEmpty &&
        holder.isEmpty &&
        image.isEmpty) {
      return const <String, dynamic>{};
    }

    return <String, dynamic>{
      'bank': bank,
      'accountType': accountType,
      'number': number,
      'holder': holder,
      'image': image,
    };
  }

  void clear() {
    bankController.clear();
    accountTypeController.clear();
    numberController.clear();
    holderController.clear();
    imageController.clear();
  }

  void dispose() {
    bankController.dispose();
    accountTypeController.dispose();
    numberController.dispose();
    holderController.dispose();
    imageController.dispose();
  }
}

class _ImageFormRow {
  _ImageFormRow({required this.urlController});

  factory _ImageFormRow.empty() {
    return _ImageFormRow(urlController: TextEditingController());
  }

  factory _ImageFormRow.fromData(CompanyImageData data) {
    return _ImageFormRow(urlController: TextEditingController(text: data.url));
  }

  final TextEditingController urlController;

  Map<String, dynamic> toJson() {
    final url = urlController.text.trim();
    if (url.isEmpty) {
      return const <String, dynamic>{};
    }

    return <String, dynamic>{'url': url};
  }

  void clear() {
    urlController.clear();
  }

  void dispose() {
    urlController.dispose();
  }
}