import 'dart:convert';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:url_launcher/url_launcher.dart';

import '../services/api_service.dart';
import '../widgets/app_text_field.dart';
import '../widgets/secondary_page_layout.dart';

class CompanyContextPage extends StatefulWidget {
  const CompanyContextPage({
    super.key,
    required this.apiService,
    required this.onConfigUpdated,
    this.onRequestBack,
    this.onMainViewChanged,
  });

  final ApiService apiService;
  final VoidCallback onConfigUpdated;
  final VoidCallback? onRequestBack;
  final ValueChanged<bool>? onMainViewChanged;

  @override
  State<CompanyContextPage> createState() => _CompanyContextPageState();
}

abstract class CompanyContextPageStateAccess {
  void openUsageRulesEditor();
}

class _CompanyContextPageState extends State<CompanyContextPage>
    implements CompanyContextPageStateAccess {
  static const Map<String, dynamic> _defaultUsageRulesTemplate =
      <String, dynamic>{
        'send_location': 'solo_si_cliente_la_pide',
        'send_bank_accounts': 'solo_si_cliente_quiere_pagar',
        'send_schedule': 'solo_si_cliente_pregunta_horario',
        'send_contact': 'solo_si_cliente_pide_contacto',
      };

  final TextEditingController _companyNameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _whatsappController = TextEditingController();
  final TextEditingController _addressController = TextEditingController();
  final TextEditingController _latitudeController = TextEditingController();
  final TextEditingController _longitudeController = TextEditingController();
  final TextEditingController _mapsLinkController = TextEditingController();
  final TextEditingController _workingHoursController = TextEditingController();
  final TextEditingController _usageRulesController = TextEditingController();

  final List<_BankAccountFormRow> _bankAccounts = <_BankAccountFormRow>[];
  final List<_ImageFormRow> _images = <_ImageFormRow>[];

  bool _isLoading = true;
  bool _isSaving = false;
  bool _isLocating = false;
  bool _isUploadingLogo = false;
  final Set<_ImageFormRow> _uploadingImages = <_ImageFormRow>{};
  final Set<_BankAccountFormRow> _uploadingBankImages = <_BankAccountFormRow>{};
  String? _lastAutoGeneratedMapsLink;
  String? _loadError;
  _CompanySection? _selectedSection;
  String _companyLogoUrl = '';
  String _brandingCompanyDetails = '';
  String _brandingCompanyName = '';

  @override
  void initState() {
    super.initState();
    _latitudeController.addListener(_syncMapsLinkPreview);
    _longitudeController.addListener(_syncMapsLinkPreview);
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        _notifyMainViewState();
      }
    });
    _loadContext();
  }

  @override
  void didUpdateWidget(covariant CompanyContextPage oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.apiService.baseUrl != widget.apiService.baseUrl) {
      _loadContext();
    }
  }

  @override
  void dispose() {
    _companyNameController.dispose();
    _descriptionController.dispose();
    _phoneController.dispose();
    _whatsappController.dispose();
    _addressController.dispose();
    _latitudeController.dispose();
    _longitudeController.dispose();
    _mapsLinkController.dispose();
    _workingHoursController.dispose();
    _usageRulesController.dispose();
    _disposeBankAccounts();
    _disposeImages();
    super.dispose();
  }

  void _notifyMainViewState() {
    widget.onMainViewChanged?.call(_selectedSection == null);
  }

  Future<void> _loadContext() async {
    setState(() {
      _isLoading = true;
      _loadError = null;
    });

    try {
      final results = await Future.wait<Object>(<Future<Object>>[
        widget.apiService.getCompanyContext(),
        widget.apiService.getConfig(),
      ]);
      final context = results[0] as CompanyContextData;
      final config = results[1] as ClientConfigData;
      _applyContext(context);
      _applyBranding(config);
    } catch (error) {
      _applyContext(CompanyContextData.empty());
      _applyBranding(ClientConfigData.empty());
      if (!mounted) {
        return;
      }

      setState(() {
        _loadError = error.toString().replaceFirst('Exception: ', '');
      });
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  void _applyBranding(ClientConfigData config) {
    _companyLogoUrl = config.companyLogoUrl;
    _brandingCompanyDetails = config.companyDetails;
    _brandingCompanyName = config.companyName;
  }

  void _applyContext(CompanyContextData context) {
    _companyNameController.text = context.companyName;
    _descriptionController.text = context.description;
    _phoneController.text = context.phone;
    _whatsappController.text = context.whatsapp;
    _addressController.text = context.address;
    _latitudeController.text = context.latitude?.toString() ?? '';
    _longitudeController.text = context.longitude?.toString() ?? '';
    _mapsLinkController.text = context.googleMapsLink;
    _lastAutoGeneratedMapsLink =
      context.googleMapsLink.trim().isNotEmpty &&
        context.googleMapsLink.trim() == _buildGeneratedMapsLinkFromCoordinates()
      ? context.googleMapsLink.trim()
      : null;
    _workingHoursController.text = _prettyJson(context.workingHoursJson);
    _usageRulesController.text = _prettyJson(context.usageRulesJson);

    _disposeBankAccounts();
    _disposeImages();

    for (final item in context.bankAccountsJson) {
      _bankAccounts.add(_BankAccountFormRow.fromData(item));
    }
    for (final item in context.imagesJson) {
      _images.add(_ImageFormRow.fromData(item));
    }

    if (_bankAccounts.isEmpty) {
      _bankAccounts.add(_BankAccountFormRow.empty());
    }
    if (_images.isEmpty) {
      _images.add(_ImageFormRow.empty());
    }

    _syncMapsLinkPreview();
  }

  Future<void> _saveContext() async {
    setState(() {
      _isSaving = true;
    });

    try {
      final workingHours = _decodeJsonMap(
        _workingHoursController.text,
        fieldName: 'Horario',
      );
      final usageRules = _decodeJsonMap(
        _usageRulesController.text,
        fieldName: 'Reglas de uso',
      );
      final latitude = _parseCoordinate(
        _latitudeController.text,
        fieldName: 'Latitud',
      );
      final longitude = _parseCoordinate(
        _longitudeController.text,
        fieldName: 'Longitud',
      );
      final bankAccounts = _bankAccounts
          .map((item) => item.toJson())
          .where((item) => item.isNotEmpty)
          .toList();
      final images = _images
          .map((item) => item.toJson())
          .where((item) => item.isNotEmpty)
          .toList();
      final normalizedCompanyName = _companyNameController.text.trim();

      final saved = await widget.apiService.saveCompanyContext(
        companyName: normalizedCompanyName,
        description: _descriptionController.text.trim(),
        phone: _phoneController.text.trim(),
        whatsapp: _whatsappController.text.trim(),
        address: _addressController.text.trim(),
        googleMapsLink: _mapsLinkController.text.trim(),
        latitude: latitude,
        longitude: longitude,
        workingHoursJson: workingHours,
        bankAccountsJson: bankAccounts,
        imagesJson: images,
        usageRulesJson: usageRules,
      );
      final brandingConfig = await widget.apiService.saveBrandingSettings(
        companyName: normalizedCompanyName.isEmpty
            ? _brandingCompanyName
            : normalizedCompanyName,
        companyDetails: _brandingCompanyDetails,
        companyLogoUrl: _companyLogoUrl.trim(),
      );

      if (!mounted) {
        return;
      }

      _applyContext(saved);
      _applyBranding(brandingConfig);
      widget.onConfigUpdated();
      _showMessage('Informacion de la empresa guardada.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _isSaving = false;
        });
      }
    }
  }

  Future<void> _pickAndUploadLogo() async {
    setState(() {
      _isUploadingLogo = true;
    });

    try {
      final result = await FilePicker.platform.pickFiles(
        allowMultiple: false,
        withData: true,
        type: FileType.custom,
        allowedExtensions: const <String>['png', 'jpg', 'jpeg', 'webp', 'svg'],
      );

      final file = result?.files.single;
      if (file == null || file.bytes == null) {
        return;
      }

      final extension = file.extension?.toLowerCase();
      final uploaded = await widget.apiService.uploadMedia(
        fileBytes: file.bytes!,
        fileName: file.name,
        contentType: extension == 'png'
            ? 'image/png'
            : extension == 'webp'
                ? 'image/webp'
                : extension == 'svg'
                    ? 'image/svg+xml'
                    : 'image/jpeg',
        title: 'Logo ${_companyNameController.text.trim().isEmpty ? 'empresa' : _companyNameController.text.trim()}',
        description: 'Logo corporativo',
      );

      if (!mounted) {
        return;
      }

      setState(() {
        _companyLogoUrl = uploaded.fileUrl;
      });
      widget.onConfigUpdated();
      _showMessage('Logo cargado. Guarda cambios para persistirlo.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _isUploadingLogo = false;
        });
      }
    }
  }

  Future<void> _captureLocation() async {
    setState(() {
      _isLocating = true;
    });

    try {
      final servicesEnabled = await Geolocator.isLocationServiceEnabled();
      if (!servicesEnabled) {
        throw Exception('Activa la ubicacion del dispositivo para obtener el GPS.');
      }

      var permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
      }

      if (permission == LocationPermission.denied ||
          permission == LocationPermission.deniedForever) {
        throw Exception('No se concedio permiso para leer la ubicacion.');
      }

      final position = await Geolocator.getCurrentPosition();
      _latitudeController.text = position.latitude.toStringAsFixed(6);
      _longitudeController.text = position.longitude.toStringAsFixed(6);
      _syncMapsLinkPreview();

      if (!mounted) {
        return;
      }

      _showMessage('Ubicacion obtenida. Guarda para persistir el enlace de mapa.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _isLocating = false;
        });
      }
    }
  }

  Future<void> _openMapsLink() async {
    final link = _mapsLinkController.text.trim();
    if (link.isEmpty) {
      _showMessage('Todavia no hay enlace de mapa disponible.', isError: true);
      return;
    }

    final launched = await launchUrl(Uri.parse(link));
    if (!launched && mounted) {
      _showMessage('No se pudo abrir Google Maps.', isError: true);
    }
  }

  @override
  void openUsageRulesEditor() {
    _showUsageRulesSheet();
  }

  Future<void> _showUsageRulesSheet() async {
    final controller = TextEditingController(text: _usageRulesEditorSeed());

    await showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      showDragHandle: true,
      builder: (context) {
        final viewInsets = MediaQuery.viewInsetsOf(context);
        return Padding(
          padding: EdgeInsets.fromLTRB(20, 12, 20, 24 + viewInsets.bottom),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              const Text(
                'Reglas de uso del bot',
                style: TextStyle(
                  color: Color(0xFF0F172A),
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: controller,
                maxLines: 12,
                decoration: const InputDecoration(),
              ),
              const SizedBox(height: 12),
              const Text(
                'Guia por defecto: ubicacion, cuentas, horario y contacto solo cuando el cliente lo pida.',
                style: TextStyle(
                  color: Color(0xFF64748B),
                  fontSize: 12,
                  height: 1.4,
                ),
              ),
              const SizedBox(height: 18),
              Wrap(
                spacing: 12,
                runSpacing: 12,
                children: <Widget>[
                  TextButton(
                    onPressed: () {
                      controller.text = _prettyJson(_defaultUsageRulesTemplate);
                    },
                    child: const Text('Usar guia por defecto'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      _usageRulesController.text = controller.text.trim();
                      Navigator.of(context).pop();
                    },
                    child: const Text('Aplicar'),
                  ),
                  OutlinedButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Cerrar'),
                  ),
                ],
              ),
            ],
          ),
        );
      },
    );

    controller.dispose();
  }

  void _addBankAccount() {
    setState(() {
      _bankAccounts.add(_BankAccountFormRow.empty());
    });
  }

  void _removeBankAccount(_BankAccountFormRow row) {
    if (_bankAccounts.length == 1) {
      row.clear();
      setState(() {});
      return;
    }

    setState(() {
      _bankAccounts.remove(row);
      row.dispose();
    });
  }

  void _addImage() {
    setState(() {
      _images.add(_ImageFormRow.empty());
    });
  }

  Future<void> _uploadImageForRow(_ImageFormRow row) async {
    setState(() {
      _uploadingImages.add(row);
    });

    try {
      final uploadedUrl = await _pickAndUploadImage(
        titlePrefix: _companyNameController.text.trim().isEmpty
            ? 'Imagen empresa'
            : 'Imagen ${_companyNameController.text.trim()}',
      );
      if (uploadedUrl == null) {
        return;
      }

      row.urlController.text = uploadedUrl;
      if (!mounted) {
        return;
      }

      _showMessage('Imagen cargada correctamente.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _uploadingImages.remove(row);
        });
      }
    }
  }

  Future<void> _uploadBankAccountImage(_BankAccountFormRow row) async {
    setState(() {
      _uploadingBankImages.add(row);
    });

    try {
      final uploadedUrl = await _pickAndUploadImage(
        titlePrefix: row.bankController.text.trim().isEmpty
            ? 'Soporte cuenta bancaria'
            : 'Soporte ${row.bankController.text.trim()}',
      );
      if (uploadedUrl == null) {
        return;
      }

      row.imageController.text = uploadedUrl;
      if (!mounted) {
        return;
      }

      _showMessage('Imagen de cuenta cargada correctamente.');
    } catch (error) {
      if (!mounted) {
        return;
      }

      _showMessage(error.toString().replaceFirst('Exception: ', ''), isError: true);
    } finally {
      if (mounted) {
        setState(() {
          _uploadingBankImages.remove(row);
        });
      }
    }
  }

  void _removeImage(_ImageFormRow row) {
    if (_images.length == 1) {
      row.clear();
      setState(() {});
      return;
    }

    setState(() {
      _images.remove(row);
      row.dispose();
    });
  }

  void _disposeBankAccounts() {
    for (final item in _bankAccounts) {
      item.dispose();
    }
    _bankAccounts.clear();
  }

  void _disposeImages() {
    for (final item in _images) {
      item.dispose();
    }
    _images.clear();
  }

  void _syncMapsLinkPreview() {
    final generated = _buildGeneratedMapsLinkFromCoordinates();
    final current = _mapsLinkController.text.trim();

    if (generated == null) {
      if (current.isEmpty || current == (_lastAutoGeneratedMapsLink ?? '')) {
        _mapsLinkController.clear();
        _lastAutoGeneratedMapsLink = null;
      }
      return;
    }

    if (current.isEmpty || current == (_lastAutoGeneratedMapsLink ?? '')) {
      _mapsLinkController.text = generated;
      _lastAutoGeneratedMapsLink = generated;
    }
  }

  String? _buildGeneratedMapsLinkFromCoordinates() {
    final latitude = double.tryParse(_latitudeController.text.trim());
    final longitude = double.tryParse(_longitudeController.text.trim());

    if (latitude == null || longitude == null) {
      return null;
    }

    return 'https://www.google.com/maps?q=$latitude,$longitude';
  }

  Future<String?> _pickAndUploadImage({required String titlePrefix}) async {
    final result = await FilePicker.platform.pickFiles(
      allowMultiple: false,
      withData: true,
      type: FileType.custom,
      allowedExtensions: const <String>['png', 'jpg', 'jpeg', 'webp', 'svg'],
    );

    final file = result?.files.single;
    if (file == null || file.bytes == null) {
      return null;
    }

    final extension = file.extension?.toLowerCase();
    if (file.size > 20 * 1024 * 1024) {
      throw Exception('La imagen supera el limite de 20MB.');
    }

    final uploaded = await widget.apiService.uploadMedia(
      fileBytes: file.bytes!,
      fileName: file.name,
      contentType: extension == 'png'
          ? 'image/png'
          : extension == 'webp'
              ? 'image/webp'
              : extension == 'svg'
                  ? 'image/svg+xml'
                  : 'image/jpeg',
      title: titlePrefix,
      description: 'Imagen asociada a informacion empresarial',
    );

    return uploaded.fileUrl;
  }

  Map<String, dynamic> _decodeJsonMap(
    String rawValue, {
    required String fieldName,
  }) {
    final trimmed = rawValue.trim();
    if (trimmed.isEmpty) {
      return <String, dynamic>{};
    }

    final decoded = jsonDecode(trimmed);
    if (decoded is! Map<String, dynamic>) {
      throw Exception('$fieldName debe ser un JSON tipo objeto.');
    }

    return decoded;
  }

  double? _parseCoordinate(String rawValue, {required String fieldName}) {
    final trimmed = rawValue.trim();
    if (trimmed.isEmpty) {
      return null;
    }

    final parsed = double.tryParse(trimmed);
    if (parsed == null) {
      throw Exception('$fieldName no es valida.');
    }

    return parsed;
  }

  String _prettyJson(Map<String, dynamic> value) {
    if (value.isEmpty) {
      return '{}';
    }

    return const JsonEncoder.withIndent('  ').convert(value);
  }

  void _showMessage(String message, {bool isError = false}) {
    final messenger = ScaffoldMessenger.of(context);
    messenger.hideCurrentSnackBar();
    messenger.showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? const Color(0xFF9F1239) : const Color(0xFF166534),
      ),
    );
  }

  void _scrollToTop() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) {
        return;
      }

      final position = Scrollable.maybeOf(context)?.position;
      if (position == null) {
        return;
      }

      position.jumpTo(0);
    });
  }

  String _usageRulesEditorSeed() {
    final current = _usageRulesController.text.trim();
    if (current.isEmpty || current == '{}') {
      return _prettyJson(_defaultUsageRulesTemplate);
    }
    return current;
  }

  String _sectionTitle(_CompanySection section) {
    switch (section) {
      case _CompanySection.basic:
        return 'Datos basicos';
      case _CompanySection.contact:
        return 'Contacto';
      case _CompanySection.location:
        return 'Ubicacion';
      case _CompanySection.schedule:
        return 'Horario';
      case _CompanySection.bankAccounts:
        return 'Cuentas bancarias';
      case _CompanySection.images:
        return 'Imagenes';
    }
  }

  String _sectionDescription(_CompanySection section) {
    switch (section) {
      case _CompanySection.basic:
        return 'Nombre y descripcion comercial.';
      case _CompanySection.contact:
        return 'Telefono y WhatsApp.';
      case _CompanySection.location:
        return 'Direccion, GPS y Google Maps.';
      case _CompanySection.schedule:
        return 'Horarios disponibles para el bot.';
      case _CompanySection.bankAccounts:
        return 'Cuentas para pagos y referencias.';
      case _CompanySection.images:
        return 'Imagenes de apoyo o de marca.';
    }
  }

  IconData _sectionIcon(_CompanySection section) {
    switch (section) {
      case _CompanySection.basic:
        return Icons.business_rounded;
      case _CompanySection.contact:
        return Icons.phone_in_talk_rounded;
      case _CompanySection.location:
        return Icons.place_rounded;
      case _CompanySection.schedule:
        return Icons.schedule_rounded;
      case _CompanySection.bankAccounts:
        return Icons.account_balance_rounded;
      case _CompanySection.images:
        return Icons.photo_library_rounded;
    }
  }

  int _nonEmptyBankAccountsCount() {
    return _bankAccounts.where((item) => item.toJson().isNotEmpty).length;
  }

  int _nonEmptyImagesCount() {
    return _images.where((item) => item.toJson().isNotEmpty).length;
  }

  String _sectionStatus(_CompanySection section) {
    switch (section) {
      case _CompanySection.basic:
        return _companyNameController.text.trim().isEmpty ? 'Pendiente' : 'Listo';
      case _CompanySection.contact:
        return _phoneController.text.trim().isEmpty &&
                _whatsappController.text.trim().isEmpty
            ? 'Pendiente'
            : 'Listo';
      case _CompanySection.location:
        return _addressController.text.trim().isEmpty &&
                _mapsLinkController.text.trim().isEmpty
            ? 'Pendiente'
            : 'Listo';
      case _CompanySection.schedule:
        return _workingHoursController.text.trim() == '{}'
            ? 'Pendiente'
            : 'Listo';
      case _CompanySection.bankAccounts:
        final count = _nonEmptyBankAccountsCount();
        return count == 0 ? 'Pendiente' : '$count cuenta${count == 1 ? '' : 's'}';
      case _CompanySection.images:
        final count = _nonEmptyImagesCount();
        return count == 0 ? 'Pendiente' : '$count imagen${count == 1 ? '' : 'es'}';
    }
  }

  List<_CompanyMenuItemData> _menuItems() {
    return <_CompanyMenuItemData>[
      for (final section in _CompanySection.values)
        _CompanyMenuItemData(
          section: section,
          title: _sectionTitle(section),
          description: _sectionDescription(section),
          status: _sectionStatus(section),
          icon: _sectionIcon(section),
        ),
    ];
  }

  Widget _buildMenuView(bool isBusy) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        if (_isLoading) ...<Widget>[
          const SizedBox(height: 4),
          const LinearProgressIndicator(minHeight: 2),
        ],
        if (_loadError != null) ...<Widget>[
          const SizedBox(height: 12),
          _CompanyMessageLine(
            message: _loadError!,
            color: const Color(0xFF9F1239),
          ),
        ],
        const SizedBox(height: 18),
        _CompanyMenuList(
          items: _menuItems(),
          enabled: !_isLoading,
          onTap: (_CompanySection section) {
            setState(() {
              _selectedSection = section;
            });
            _notifyMainViewState();
            _scrollToTop();
          },
        ),
      ],
    );
  }

  Widget _buildDetailView(_CompanySection section, bool isBusy) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _CompanyDetailHeader(
          title: _sectionTitle(section),
          subtitle: _sectionDescription(section),
          onBack: () {
            setState(() {
              _selectedSection = null;
            });
            _notifyMainViewState();
            _scrollToTop();
          },
          onReload: isBusy ? null : _loadContext,
        ),
        if (_loadError != null) ...<Widget>[
          const SizedBox(height: 12),
          _CompanyMessageLine(
            message: _loadError!,
            color: const Color(0xFF9F1239),
          ),
        ],
        const SizedBox(height: 18),
        switch (section) {
          _CompanySection.basic => _buildBasicDataSection(isBusy),
          _CompanySection.contact => _buildContactSection(isBusy),
          _CompanySection.location => _buildLocationSection(isBusy),
          _CompanySection.schedule => _buildWorkingHoursSection(isBusy),
          _CompanySection.bankAccounts => _buildBankAccountsSection(isBusy),
          _CompanySection.images => _buildImagesSection(isBusy),
        },
        const SizedBox(height: 24),
        Wrap(
          spacing: 12,
          runSpacing: 12,
          children: <Widget>[
            ElevatedButton(
              onPressed: isBusy ? null : _saveContext,
              child: Text(_isSaving ? 'Guardando...' : 'Guardar cambios'),
            ),
            OutlinedButton(
              onPressed: isBusy
                  ? null
                  : () {
                      setState(() {
                        _selectedSection = null;
                      });
                      _notifyMainViewState();
                      _scrollToTop();
                    },
              child: const Text('Volver a empresa'),
            ),
          ],
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final isBusy = _isLoading || _isSaving;
    final selectedSection = _selectedSection;

    return SecondaryPageLayout(
      caption: null,
      child: selectedSection == null
          ? _buildMenuView(isBusy)
          : _buildDetailView(selectedSection, isBusy),
    );
  }

  Widget _buildBasicDataSection(bool isBusy) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final fullWidth = constraints.maxWidth;
        final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

        return Wrap(
          spacing: 18,
          runSpacing: 18,
          children: <Widget>[
            SizedBox(
              width: fullWidth,
              child: _CompanyLogoField(
                logoUrl: _companyLogoUrl,
                enabled: !isBusy,
                isUploading: _isUploadingLogo,
                onUpload: _pickAndUploadLogo,
              ),
            ),
            SizedBox(
              width: halfWidth,
              child: AppTextField(
                label: 'Nombre comercial',
                controller: _companyNameController,
                enabled: !isBusy,
                hintText: 'Phyto Emagry',
                helperText: 'Ejemplo: Phyto Emagry RD',
              ),
            ),
            SizedBox(
              width: fullWidth,
              child: AppTextField(
                label: 'Descripcion',
                controller: _descriptionController,
                enabled: !isBusy,
                maxLines: 4,
                hintText: 'Resumen corto de la empresa y lo que ofrece.',
                helperText: 'Breve y claro.',
              ),
            ),
          ],
        );
      },
    );
  }

  Widget _buildContactSection(bool isBusy) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final fullWidth = constraints.maxWidth;
        final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

        return Wrap(
          spacing: 18,
          runSpacing: 18,
          children: <Widget>[
            SizedBox(
              width: halfWidth,
              child: AppTextField(
                label: 'Telefono',
                controller: _phoneController,
                enabled: !isBusy,
                hintText: '809-555-1234',
                helperText: 'Linea principal.',
              ),
            ),
            SizedBox(
              width: halfWidth,
              child: AppTextField(
                label: 'WhatsApp',
                controller: _whatsappController,
                enabled: !isBusy,
                hintText: '+18095551234',
                helperText: 'Numero con codigo.',
              ),
            ),
          ],
        );
      },
    );
  }

  Widget _buildLocationSection(bool isBusy) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        AppTextField(
          label: 'Direccion',
          controller: _addressController,
          enabled: !isBusy,
          maxLines: 2,
          hintText: 'Direccion fisica o punto de referencia.',
          helperText: 'Sucursal o referencia principal.',
        ),
        const SizedBox(height: 18),
        LayoutBuilder(
          builder: (context, constraints) {
            final fullWidth = constraints.maxWidth;
            final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

            return Wrap(
              spacing: 18,
              runSpacing: 18,
              children: <Widget>[
                SizedBox(
                  width: halfWidth,
                  child: AppTextField(
                    label: 'Latitud',
                    controller: _latitudeController,
                    enabled: !isBusy,
                    keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: true),
                    hintText: '18.486058',
                    helperText: 'Valor GPS.',
                  ),
                ),
                SizedBox(
                  width: halfWidth,
                  child: AppTextField(
                    label: 'Longitud',
                    controller: _longitudeController,
                    enabled: !isBusy,
                    keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: true),
                    hintText: '-69.931212',
                    helperText: 'Valor GPS.',
                  ),
                ),
                SizedBox(
                  width: fullWidth,
                  child: AppTextField(
                    label: 'Link de Google Maps',
                    controller: _mapsLinkController,
                    enabled: !isBusy,
                    helperText: 'Puedes pegarlo manualmente o generarlo con GPS.',
                    hintText: 'https://www.google.com/maps?q=...',
                  ),
                ),
              ],
            );
          },
        ),
        const SizedBox(height: 18),
        Wrap(
          spacing: 12,
          runSpacing: 12,
          children: <Widget>[
            ElevatedButton.icon(
              onPressed: isBusy || _isLocating ? null : _captureLocation,
              icon: Icon(_isLocating ? Icons.gps_not_fixed_rounded : Icons.my_location_rounded),
              label: Text(_isLocating ? 'Obteniendo ubicacion...' : 'Obtener ubicacion'),
            ),
            OutlinedButton.icon(
              onPressed: _mapsLinkController.text.trim().isEmpty ? null : _openMapsLink,
              icon: const Icon(Icons.map_outlined),
              label: const Text('Abrir mapa'),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildWorkingHoursSection(bool isBusy) {
    return AppTextField(
      label: 'working_hours_json',
      controller: _workingHoursController,
      enabled: !isBusy,
      maxLines: 8,
      hintText: '{\n  "lunes_viernes": "8:00 AM - 6:00 PM",\n  "sabado": "9:00 AM - 1:00 PM"\n}',
      helperText: 'Guarda el horario como JSON.',
    );
  }

  Widget _buildBankAccountsSection(bool isBusy) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        for (final item in _bankAccounts) ...<Widget>[
          _BankAccountCard(
            row: item,
            enabled: !isBusy,
            isUploadingImage: _uploadingBankImages.contains(item),
            onUploadImage: () => _uploadBankAccountImage(item),
            onRemove: () => _removeBankAccount(item),
          ),
          const SizedBox(height: 14),
        ],
        OutlinedButton.icon(
          onPressed: isBusy ? null : _addBankAccount,
          icon: const Icon(Icons.add_rounded),
          label: const Text('Agregar cuenta bancaria'),
        ),
      ],
    );
  }

  Widget _buildImagesSection(bool isBusy) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        for (final item in _images) ...<Widget>[
          _ImageRowCard(
            row: item,
            enabled: !isBusy,
            isUploading: _uploadingImages.contains(item),
            onUpload: () => _uploadImageForRow(item),
            onRemove: () => _removeImage(item),
          ),
          const SizedBox(height: 14),
        ],
        OutlinedButton.icon(
          onPressed: isBusy ? null : _addImage,
          icon: const Icon(Icons.add_photo_alternate_outlined),
          label: const Text('Agregar imagen'),
        ),
      ],
    );
  }
}

class _BankAccountCard extends StatelessWidget {
  const _BankAccountCard({
    required this.row,
    required this.enabled,
    required this.isUploadingImage,
    required this.onUploadImage,
    required this.onRemove,
  });

  final _BankAccountFormRow row;
  final bool enabled;
  final bool isUploadingImage;
  final VoidCallback onUploadImage;
  final VoidCallback onRemove;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: LayoutBuilder(
        builder: (context, constraints) {
          final fullWidth = constraints.maxWidth;
          final halfWidth = fullWidth > 640 ? (fullWidth - 18) / 2 : fullWidth;

          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Wrap(
                spacing: 18,
                runSpacing: 18,
                children: <Widget>[
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Banco',
                      controller: row.bankController,
                      enabled: enabled,
                      helperText: 'Ejemplo: Banreservas',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Tipo de cuenta',
                      controller: row.accountTypeController,
                      enabled: enabled,
                      helperText: 'Ejemplo: Ahorro o Corriente',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Numero',
                      controller: row.numberController,
                      enabled: enabled,
                      helperText: 'Ejemplo: 123456789',
                    ),
                  ),
                  SizedBox(
                    width: halfWidth,
                    child: AppTextField(
                      label: 'Titular',
                      controller: row.holderController,
                      enabled: enabled,
                      helperText: 'Ejemplo: Phyto Emagry SRL',
                    ),
                  ),
                  SizedBox(
                    width: fullWidth,
                    child: AppTextField(
                      label: 'Imagen opcional',
                      controller: row.imageController,
                      enabled: enabled,
                      hintText: 'https://...',
                      helperText: 'Puedes pegar una URL o usar el boton de abajo para subir la imagen aqui mismo.',
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 14),
              Align(
                alignment: Alignment.centerRight,
                child: Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  alignment: WrapAlignment.end,
                  children: <Widget>[
                    OutlinedButton.icon(
                      onPressed: enabled && !isUploadingImage ? onUploadImage : null,
                      icon: Icon(
                        isUploadingImage
                            ? Icons.cloud_upload_outlined
                            : Icons.upload_file_rounded,
                      ),
                      label: Text(
                        isUploadingImage ? 'Subiendo imagen...' : 'Subir imagen aqui',
                      ),
                    ),
                    TextButton.icon(
                      onPressed: enabled ? onRemove : null,
                      icon: const Icon(Icons.delete_outline_rounded),
                      label: const Text('Quitar cuenta'),
                    ),
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}

class _ImageRowCard extends StatelessWidget {
  const _ImageRowCard({
    required this.row,
    required this.enabled,
    required this.isUploading,
    required this.onUpload,
    required this.onRemove,
  });

  final _ImageFormRow row;
  final bool enabled;
  final bool isUploading;
  final VoidCallback onUpload;
  final VoidCallback onRemove;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          AppTextField(
            label: 'URL de imagen',
            controller: row.urlController,
            enabled: enabled,
            hintText: 'https://...',
            helperText: 'Puedes pegar una URL o usar el boton para subir la imagen.',
          ),
          const SizedBox(height: 10),
          Align(
            alignment: Alignment.centerRight,
            child: Wrap(
              spacing: 8,
              runSpacing: 8,
              alignment: WrapAlignment.end,
              children: <Widget>[
                OutlinedButton.icon(
                  onPressed: enabled && !isUploading ? onUpload : null,
                  icon: Icon(
                    isUploading
                        ? Icons.cloud_upload_outlined
                        : Icons.upload_file_rounded,
                  ),
                  label: Text(isUploading ? 'Subiendo...' : 'Subir imagen'),
                ),
                TextButton.icon(
                  onPressed: enabled ? onRemove : null,
                  icon: const Icon(Icons.delete_outline_rounded),
                  label: const Text('Quitar imagen'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _BankAccountFormRow {
  _BankAccountFormRow({
    required this.bankController,
    required this.accountTypeController,
    required this.numberController,
    required this.holderController,
    required this.imageController,
  });

  factory _BankAccountFormRow.empty() {
    return _BankAccountFormRow(
      bankController: TextEditingController(),
      accountTypeController: TextEditingController(),
      numberController: TextEditingController(),
      holderController: TextEditingController(),
      imageController: TextEditingController(),
    );
  }

  factory _BankAccountFormRow.fromData(CompanyBankAccountData data) {
    return _BankAccountFormRow(
      bankController: TextEditingController(text: data.bank),
      accountTypeController: TextEditingController(text: data.accountType),
      numberController: TextEditingController(text: data.number),
      holderController: TextEditingController(text: data.holder),
      imageController: TextEditingController(text: data.image),
    );
  }

  final TextEditingController bankController;
  final TextEditingController accountTypeController;
  final TextEditingController numberController;
  final TextEditingController holderController;
  final TextEditingController imageController;

  Map<String, dynamic> toJson() {
    final bank = bankController.text.trim();
    final accountType = accountTypeController.text.trim();
    final number = numberController.text.trim();
    final holder = holderController.text.trim();
    final image = imageController.text.trim();

    if (bank.isEmpty &&
        accountType.isEmpty &&
        number.isEmpty &&
        holder.isEmpty &&
        image.isEmpty) {
      return const <String, dynamic>{};
    }

    return <String, dynamic>{
      'bank': bank,
      'accountType': accountType,
      'number': number,
      'holder': holder,
      'image': image,
    };
  }

  void clear() {
    bankController.clear();
    accountTypeController.clear();
    numberController.clear();
    holderController.clear();
    imageController.clear();
  }

  void dispose() {
    bankController.dispose();
    accountTypeController.dispose();
    numberController.dispose();
    holderController.dispose();
    imageController.dispose();
  }
}

class _ImageFormRow {
  _ImageFormRow({required this.urlController});

  factory _ImageFormRow.empty() {
    return _ImageFormRow(urlController: TextEditingController());
  }

  factory _ImageFormRow.fromData(CompanyImageData data) {
    return _ImageFormRow(urlController: TextEditingController(text: data.url));
  }

  final TextEditingController urlController;

  Map<String, dynamic> toJson() {
    final url = urlController.text.trim();
    if (url.isEmpty) {
      return const <String, dynamic>{};
    }

    return <String, dynamic>{'url': url};
  }

  void clear() {
    urlController.clear();
  }

  void dispose() {
    urlController.dispose();
  }
}

enum _CompanySection {
  basic,
  contact,
  location,
  schedule,
  bankAccounts,
  images,
}

class _CompanyMenuItemData {
  const _CompanyMenuItemData({
    required this.section,
    required this.title,
    required this.description,
    required this.status,
    required this.icon,
  });

  final _CompanySection section;
  final String title;
  final String description;
  final String status;
  final IconData icon;
}

class _CompanyMenuList extends StatelessWidget {
  const _CompanyMenuList({
    required this.items,
    required this.enabled,
    required this.onTap,
  });

  final List<_CompanyMenuItemData> items;
  final bool enabled;
  final ValueChanged<_CompanySection> onTap;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: items
          .asMap()
          .entries
          .expand((entry) => <Widget>[
                _CompanyMenuTile(
                  item: entry.value,
                  enabled: enabled,
                  onTap: () => onTap(entry.value.section),
                ),
                if (entry.key < items.length - 1)
                  const Divider(height: 1, color: Color(0xFFE2E8F0)),
              ])
          .toList(),
    );
  }
}

class _CompanyMenuTile extends StatelessWidget {
  const _CompanyMenuTile({
    required this.item,
    required this.enabled,
    required this.onTap,
  });

  final _CompanyMenuItemData item;
  final bool enabled;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: enabled ? onTap : null,
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 14),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Icon(item.icon, size: 20, color: const Color(0xFF2563EB)),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    item.title,
                    style: const TextStyle(
                      color: Color(0xFF0F172A),
                      fontSize: 15,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    item.description,
                    style: const TextStyle(
                      color: Color(0xFF64748B),
                      fontSize: 12,
                      height: 1.4,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(width: 12),
            Text(
              item.status,
              style: const TextStyle(
                color: Color(0xFF475569),
                fontSize: 12,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(width: 8),
            const Icon(
              Icons.chevron_right_rounded,
              color: Color(0xFF94A3B8),
            ),
          ],
        ),
      ),
    );
  }
}

class _CompanyDetailHeader extends StatelessWidget {
  const _CompanyDetailHeader({
    required this.title,
    required this.subtitle,
    required this.onBack,
    required this.onReload,
  });

  final String title;
  final String subtitle;
  final VoidCallback onBack;
  final VoidCallback? onReload;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Row(
          children: <Widget>[
            TextButton.icon(
              onPressed: onBack,
              icon: const Icon(Icons.arrow_back_rounded, size: 18),
              label: const Text('Empresa'),
            ),
            const Spacer(),
            TextButton(
              onPressed: onReload,
              child: const Text('Recargar'),
            ),
          ],
        ),
        const SizedBox(height: 8),
        Text(
          title,
          style: const TextStyle(
            color: Color(0xFF0F172A),
            fontSize: 24,
            fontWeight: FontWeight.w800,
          ),
        ),
        const SizedBox(height: 6),
        Text(
          subtitle,
          style: const TextStyle(
            color: Color(0xFF64748B),
            fontSize: 13,
            height: 1.45,
          ),
        ),
      ],
    );
  }
}

class _CompanyMessageLine extends StatelessWidget {
  const _CompanyMessageLine({required this.message, required this.color});

  final String message;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Icon(Icons.info_outline_rounded, size: 16, color: color),
        const SizedBox(width: 8),
        Expanded(
          child: Text(
            message,
            style: TextStyle(
              color: color,
              fontSize: 12,
              fontWeight: FontWeight.w600,
              height: 1.4,
            ),
          ),
        ),
      ],
    );
  }
}

class _CompanyLogoField extends StatelessWidget {
  const _CompanyLogoField({
    required this.logoUrl,
    required this.enabled,
    required this.isUploading,
    required this.onUpload,
  });

  final String logoUrl;
  final bool enabled;
  final bool isUploading;
  final VoidCallback onUpload;

  @override
  Widget build(BuildContext context) {
    final hasLogo = logoUrl.trim().isNotEmpty;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Row(
        children: <Widget>[
          Container(
            width: 68,
            height: 68,
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(18),
              border: Border.all(color: const Color(0xFFE2E8F0)),
            ),
            clipBehavior: Clip.antiAlias,
            child: hasLogo
                ? Image.network(
                    logoUrl,
                    fit: BoxFit.cover,
                    errorBuilder: (context, error, stackTrace) {
                      return const Icon(
                        Icons.business_rounded,
                        color: Color(0xFF94A3B8),
                        size: 28,
                      );
                    },
                  )
                : const Icon(
                    Icons.business_rounded,
                    color: Color(0xFF94A3B8),
                    size: 28,
                  ),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                const Text(
                  'Logo',
                  style: TextStyle(
                    color: Color(0xFF0F172A),
                    fontSize: 14,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  hasLogo ? 'Logo listo para guardar.' : 'Sube el logo al storage.',
                  style: const TextStyle(
                    color: Color(0xFF64748B),
                    fontSize: 12,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(width: 12),
          OutlinedButton.icon(
            onPressed: enabled && !isUploading ? onUpload : null,
            icon: Icon(
              isUploading ? Icons.cloud_upload_outlined : Icons.upload_file_rounded,
            ),
            label: Text(isUploading ? 'Subiendo...' : hasLogo ? 'Cambiar' : 'Subir'),
          ),
        ],
      ),
    );
  }
}